### ISSUE TITLE
Flutter redux state changes not updating immediately

### ISSUE THREAD

**Issue by Rajakalla** [brianegan/flutter_redux#103]
Hi,

I am new to flutter and redux. This library/package is very useful .But I am facing a problem with state updating in flutter widget. Without including redux , I have learnt that `setState`  will automatically updates the UI widget tree. 
But using redux library/ package not updating immeditely untill all the statements are executed.

The below is the example of my issue :
`(){
store.dispatch(FirstAction());                                                                                                              
store.dispatch(SecondAction());
store.dispatch(ThirdAction());
}`

Here the first action should change the UI widget tree immediately ,then the second action should be done then after the third action.
My 1st and 3rd actions are circularprogress bar indicator, and the second action is fetching data (http request).without changing the UI to circular progress bar indicator it performing the second action.
I hope a quick solution for my problem .
Thank you

**Comment by brianegan** [comment]
Hey there -- are you synchronously dispatching all of these actions one after the next? 

If so, that's probably the issue: Flutter may or may not re-render after each statement. Why? Because `setState` doesn't TRIGGER a rebuild, it *marks* the Widget as needing a rebuild. 

Flutter will then schedule the repaint to happen on the next Frame draw. If all of these actions happen before the next frame draw (which is very likely if they're all synchronous), then you won't see Flutter redraw the intermediate states.

In fact, you can do the exact same thing without Redux! Just use `setState` three times in the same method on after the next, and you'll see the UI only renders the final `setState` data.

If you're not calling these things synchronously, please let me know and I'll see if I can figure out the problem!

Example using only setState and seeing the same behavior: https://gist.github.com/42b7e2ef856ca8f82f84c62cba46b2d4

**Comment by Rajakalla** [comment]
Thank you for your quick response. 
But when i used `setState`  three time like below it worked fine(`isCircularProgressBarLoading:true` loaded the CircularProgressBar before the next statement ).
`funtion(){`
`.......`
`setState({isCircularProgressBarLoading:true});`
`await AadOAuth.login();`
`at=await oauth.getAccessToken();`
`setState({isCircularProgressBarLoading:true});`
`.......`
`}`

**Comment by brianegan** [comment]
Yep -- that is adding some time in between each setState call. Therefore, Flutter is rendering the intermediate states. The same thing should work with Redux -- e.g. if you performed `store.dispatch` calls instead of `setState` it should work the exact same. Is that not the case?

**Comment by Rajakalla** [comment]
I used the same way but it worked in different way. But i understood a little about how the redux state works. 
Thank you.

**Comment by amercobra** [comment]
Hi Brian,

I'm having the same issue of not updating the my VM immediately after my Store is updated from an action executed within a Stream. I can see my store model gets updated, however it does not reflect on UI immedidately.

I'm not sure what you meant by "are you synchronously dispatching all of these actions"< i'm executing the following code to dispatch my action which updates the model:

`void _loadLastDataFromStream(Store<AppState> store, action, NextDispatcher next) async {
  next(action);

  try {
    //keeps looping and receive data from API in a Stream
    LoadLastDataStream().stream.listen(
          (chats){
            if(chats.length > 0)
                store.dispatch(new SaveLastDataInModelAction(chats)); //This actually gets really called and Model get updated with the data
      },
    );

  } catch (error) {
    store.dispatch(new LoadDataFailAction(error.message));
  }
}`

Any idea?

**Comment by amercobra** [comment]
Hello @brianegan , 

After reading what you wrote more carefully I realized that _dispatching_ my _action_ when _listening_ to a _stream_ would not actually update the UI immediately, exactly as if I'm calling _setState()_ multiple times as per your example. 

But what's the solution? I'm listening to a _Stream_ where it should update the UI each time I receive data from the Stream. I get my store state updated correctly as expected when dispatching the action with data from Stream, however UI doesn't get updated.

Thank you!
