### ISSUE TITLE
Middleware that needs to persist an API object?

### ISSUE THREAD

**Issue by naiveai** [brianegan/flutter_redux#130]
I have a piece of middleware that connects to the Reddit API and provides various functionality required for the whole app. However, my usecase requires an OAuth2 flow to work. Oauth on its own is not my issue here, I've got a workflow that works well - but as you may know, it is complicated.

The relevant issue here is that I need to create an API object that can be used throughout the app that's already authenticated through the sign-in process. So far I'm storing that API object in the middleware, but I'm afraid I'm beginning to mix too many concerns here - my RedditMiddleware ends up having to deal with sign in and recieving the redirect URL request back from Reddit, asking for the token, providing all the actual API functionality like asking for comments or checking a subreddit or whatever, and also have to deal with persisting these API credentials to secure storage so that we don't have to sign in everytime.

Is there a clean way to separate these concerns efficiently, while still being able to use the API object?

**Comment by miquelbeltran** [comment]
You can split your Middleware in multiple files. At the end, a Middleware is a collection of functions that process actions, so you could have a reddit_middleware and a login_middleware, and then chain them in the Store creation. Like:

```
    store = Store<AppState>(
      appReducer,
      initialState: AppState.init(),
      middleware: createRedditMiddleware(
        RedditRepository(),
      )
        ..addAll(createAuthenticationMiddleware(
          SettingsRepository(),
          RedditRepository(),
        ))
```

Then you can load the API object on app start (so dispatch an action on app creation), load it in your AuthenticationMiddleare, then keep it in the AppState, and use it from the RedditMiddleware

**Comment by SGuzel** [comment]
Hi, i have a similar situation. In my case, I have an grpc client instance which will be stored in the middleware. But in between the user can switch to a nother ip address via a login page and this creates a new grpc client. But the middleware do not get the newest instance and uses the old one with depracated ip address. 

As the user presses login, I thought that I am creating the whole` mainApp( ) : store = Store<AppState>( ... middleware: createStoreMiddleware(new GrpcClient). .. `

Any ideas how I can reset the middleware?

**Comment by brianegan** [comment]
@SGuzel I can think of a couple solutions:

  1. Save the GRPC client in your `State` object so the Middleware can read it `state.grpcClient` or something. When the user logs in, dispatch the new IP and have a reducer create and store the updated GRPC client. The Middleware could also listen for that action if it needs to clean up any old StreamSubscriptions and subscribe to the new client (not sure if this is a Streaming GRPC client or a Request/Response only version).
  2. Save the GRPC client in your Middleware, and when the user logs in, have the Middleware intercept that action and recreate the GRPC client.
  3. Instead of passing the GRPC client to the Middleware, pass a `GrpcClientManager` to your Middleware instead of the GrpcClient itself. That class would contain a method `grpcClient()` that returns a GrpcClient for the Middleware to use. When the user logs in, update the GrpcClientManager to store a new version of the client with the correct IP. This feels probably the least "Reduxy," but would also work.

**Comment by brianegan** [comment]
> But I do want to have the control of the listening streams and broken stream etc.

Yah, sounds like it's probably a good idea to store the `StreamSubscription`s in your Middleware when you first subscribe. If you get a new GRPC client, the Middleware should listen for the actions that could change the client. When the client is changed, it could `cancel` the old StreamSubscription then `listen` to the new `GrpcClient` for updates. That way if you're ever changing things up, you know that you need to tear down and resubscribe to something new and aren't leaving any old subscriptions around.

**Comment by SGuzel** [comment]
> Yah, sounds like it's probably a good idea to store the `StreamSubscription`s in your Middleware 
> 
> Hope that helps!

Thanks, I am storing my subscriptions in my middleware. That works.
