### ISSUE TITLE
distinct property not work, always execute rebuilt function

### ISSUE THREAD

**Issue by javico2609** [brianegan/flutter_redux#137]
```
StoreConnector<AppState, HomeViewModel>(
    distinct: true,
    converter: (store) => HomeViewModel.fromStore(store),
    builder: (_, vm) {
       print(vm.uuid);
       return Container();
   })

class HomeViewModel {
  final String uuid;

  HomeViewModel({
    this.uuid,
  });

  static HomeViewModel fromStore(Store<AppState> store) {
    return HomeViewModel(
      uuid: store.state.currencyPoolState.uuid,
    );
  }

  @override
  int get hashCode => uuid.hashCode;

  bool operator ==(other) {
    bool result = identical(this, other) || other is HomeViewModel;

    if (result) {
      if (uuid != (other as HomeViewModel).uuid) {
        return false;
      }
    }

    return result;
  }
 }
```

**Comment by Taym95** [comment]
Please give a reproduce repo, so we can debug and help!

**Comment by javico2609** [comment]
Hi.

https://github.com/javico2609/flutter-challenges/blob/63af346ab47b30b069ccc7114497e2799c8a913a/lib/pages/code_examples/redux/redux_flutter.dart#L24

**Comment by hffmnn** [comment]
@javico2609 I tried to reproduce your bug (because when looking at one of my projects I also could see that from time to time but not always). With the linked PR from above, where I added a VM that returns true for every equality check, everything worked as expected: The Widget got never rebuild.

When playing around with your example, it behaves as you describe, but I think the problem is, that the `_ReduxFlutterState` `build` method gets called, means the complete Widget gets rebuild and because of this also the `StoreConnector`.

Does that make sense?

**Comment by javico2609** [comment]
Hi @hffmnn , I have not idea, very weird behavior.

**Comment by brianegan** [comment]
Hey @javico2609 and @hffmnn -- Thanks so much for writing in and helping. Yep, when you navigate, Flutter will often run a full rebuild of the Widget tree for screens that are currently in the navigation stack -- even if they're not visible. 

It's a bit confusing at first, but it sounds like it's definitely the cause in this case. Whether you're using Redux or any architecture, you'd see those same rebuilds.

Thanks for reporting the issue, and if you run into more trouble please let us know!
