### ISSUE TITLE
onDidChange called after State dispose

### ISSUE THREAD

**Issue by llooz** [brianegan/flutter_redux#164]
`onDidChange` sometimes is called after `onDispose`.

I think that's because internally the `_StoreStreamListenerState` doesn't use a cancellable `StreamSubscription` to listen on the `onChange` of the `store`.

**Comment by muzzah** [comment]
Did you find a solution to this @llooz ? I am using ```pushReplacementNamed``` to push a new route but the onDidChange listener is still being caused from the old widget that has been disposed since I get the folllowing error

```
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

````

Would be great if the devs chimed in as there are 2 issues about this and it seems like a serious bug with no attenion

**Comment by brianegan** [comment]
Heya Mustafa -- how's life man? Hope you're well.

So folks know: I haven't had as much time for open source over the past year or so, and that's why issues like this are around. However, I need to update the library for null safety soon and I can certainly write up a test case & fix for this issue.

**Comment by muzzah** [comment]
Haha Brian I did not even realise this was you :) Im good, hope you are well as well. Im actually trying to track the source of this down and im not sure if it is in this library or another one related to managing routes. Once I track down the source I can let you know. Reason I suspect this is because changing the way I pushed and replaced the route made the issue go away but not sure if that is just a side effect :)

**Comment by brianegan** [comment]
Oh yah, I'd bet my money on this library :) `onDidChange` is an asynchronous callback and may be invoked after a Widget is disposed. You can see how it works here: https://github.com/brianegan/flutter_redux/blob/master/lib/flutter_redux.dart#L550-L554

It looks like the StoreConnector is being synchronously disposed as part of the navigation change, then trying to do something with a disposed widget in the async callback.

To fix, I need to add a check to the async callback that verifies if the Widget is still active before calling onDidChange.

**Comment by brianegan** [comment]
Fixed in latest version
