### ISSUE TITLE
How to not accept change notifications when the Router is not at the top level, and then take the initiative to obtain the changes when the Router returns to the top level

### ISSUE THREAD

**Issue by T-Oner** [brianegan/flutter_redux#223]
This may improve performance and is more suitable for certain business scenarios

**Comment by brianegan** [comment]
I haven't done this myself since I haven't measured any severe performance impacts in my own apps, but you could set `maintainState` property to `false` when navigating between routes. This has some caveats, of course, but as long as you're aware of them it could help out.

https://api.flutter.dev/flutter/widgets/ModalRoute/maintainState.html
