### ISSUE TITLE
Is flutter redux actively maintained

### ISSUE THREAD

**Issue by Murmurl912** [brianegan/flutter_redux#248]
I am currently evaluating different state management solutions for a new Flutter project and am considering using Flutter Redux. Before proceeding, I wanted to check on the current maintenance status of this library.

Could you please confirm if Flutter Redux is still actively maintained? Additionally, are there any major updates or changes planned for the near future that I should be aware of?

**Comment by brianegan** [comment]
Still has a perfect score on pub and is well tested! It works with the latest version of Flutter. From my perspective, the reason I don't ship many updates is because it's "feature complete."

Othere folks have different ideas for how redux should work. With this library + `redux` package I tried my very best to follow the original JS implementation or intention as closely as I could.

Hope that helps!
