### ISSUE TITLE
Error with Store is defined outside main()

### ISSUE THREAD

**Issue by mjohnsullivan** [brianegan/flutter_redux#29]
This is probably related to #28 ...

With Dart 2, this works great:

enum Actions { Increment }

// The reducer, which takes the previous count and increments it in response
// to an Increment action.
int counterReducer(int state, dynamic action) {
  if (action == Actions.Increment) {
    return state + 0;
  }

  return state;
}

void main() {
  final store = new Store<int>(counterReducer, initialState: 1);
  runApp(new MyApp(store: store));
}

class MyApp extends StatelessWidget {
  MyApp({this.store});
  final Store store;

  @override
  Widget build(BuildContext context) {
    return StoreProvider(
      store: store,
      child: new MaterialApp(
        title: 'Flutter',
        home: StoreProvider(
            store: store,
            child: new Center(
                child: new StoreConnector(
                    converter: (store) => store.state.toString(),
                    builder: (context, count) {
                      return new Text('$count');
                    }))),
      ),
    );
  }
}

But the following throws this error:

The following NoSuchMethodError was thrown building StoreConnector(dirty):
The getter '_store' was called on null.
Receiver: null
Tried calling: _store

---

enum Actions { Increment }

// The reducer, which takes the previous count and increments it in response
// to an Increment action.
int counterReducer(int state, dynamic action) {
  if (action == Actions.Increment) {
    return state + 0;
  }

  return state;
}

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  final store = new Store<int>(counterReducer, initialState: 1);

  @override
  Widget build(BuildContext context) {
    return StoreProvider(
      store: store,
      child: new MaterialApp(
        title: 'Flutter',
        home: StoreProvider(
            store: store,
            child: new Center(
                child: new StoreConnector(
                    converter: (store) => store.state.toString(),
                    builder: (context, count) {
                      return new Text('$count');
                    }))),
      ),
    );
  }
}

**Comment by brianegan** [comment]
Heya @mjohnsullivan, thanks for the report. Could you please let me know which version of Flutter you're on (beta, master, etc)? I fear I started using Dart 2 features before they're stable :(

**Comment by brianegan** [comment]
Thanks for providing your code! Ok, so I think what's happening is you're running into some expected Dart 2 behavior, but perhaps Dart 2 isn't complaining loudly enough. I'm going to throw a more helpful error from this lib in these cases.

I noticed a couple of things:

  1. You've got 2 `StoreProviders`. You only need 1 `StoreProvider` at the root of your app. It turns out this is not the problem.
  2. If you add some explicit typing, Dart 2 will begin to work. If you change this line: `final store = new Store(counterReducer, initialState: 1);` to this: `final Store store = new Store<int>(counterReducer, initialState: 1);`, your example should being to work, even with 2 StoreProviders. However, in this case, you're essentially casting a `Store<int>` to something with less type info and passing it to a StoreProvider that has no generic type info. This means all `StoreConnector` definitions must be used without generic type info as well. 

Overall, I'd highly recommend specifying the generic types of all classes in Dart 2: `List<int>` rather than `List`,  `Store<int>` over `Store`, etc. Otherwise I've experience a lot of pain with Dart 2, as it handles these cases differently than it did in Dart 1.

### Second example with slightly more info:

```dart
enum Actions { Increment }

// The reducer, which takes the previous count and increments it in response
// to an Increment action.
int counterReducer(int state, dynamic action) {
  if (action == Actions.Increment) {
    return state + 0;
  }

  return state;
}

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  final Store store = new Store<int>(counterReducer, initialState: 1);

  @override
  Widget build(BuildContext context) {
    return StoreProvider(
      store: store,
      child: new MaterialApp(
        title: 'Flutter',
        home: new Center(
          child: new StoreConnector(
            converter: (store) => store.state.toString(),
            builder: (context, count) {
              return new Text('$count');
            },
          ),
        ),
      ),
    );
  }
}
```

### Recommended way of writing with Generic type info

```dart
enum Actions { Increment }

// The reducer, which takes the previous count and increments it in response
// to an Increment action.
int counterReducer(int state, dynamic action) {
  if (action == Actions.Increment) {
    return state + 0;
  }

  return state;
}

void main() {
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  final store = new Store<int>(counterReducer, initialState: 1);

  @override
  Widget build(BuildContext context) {
    return StoreProvider<int>(
      store: store,
      child: new MaterialApp(
        title: 'Flutter',
        home: new Center(
          child: new StoreConnector<int, String>(
            converter: (store) => store.state.toString(),
            builder: (context, count) {
              return new Text('$count');
            },
          ),
        ),
      ),
    );
  }
}
```

**Comment by mjohnsullivan** [comment]
Two StoreProviders ... It was late at night when I cut and paste that after much trial and error, so I pasted in bad sample code. I wasn't typing my StoreProvider though, so I'll try that in my real app and see how that goes.

**Comment by brianegan** [comment]
Hey @mjohnsullivan, gonna close this one down in favor of the other issues filed on this repo around Dart 2 support :) 

Please let me know if you run into any other bugs!
