### ISSUE TITLE
onInitialBuild called multiple time on child container when parent container changes

### ISSUE THREAD

**Issue by AlexandreRoba** [brianegan/flutter_redux#59]
Hi all, I have a question regarding container that have other container. Basically I have a container that can display loading status and error message. It is a sort of "shell" container. On this container I have a child container with its own viewmodel and nothing shared. I can see the onInitialBuild method on the child container is called every time the mainshell onInitialBuild is changed. Is this an expected behavior?

**Comment by brianegan** [comment]
Sounds like a bug! Hrm, I'm curious as to why this could be happening... I'll have to take a closer look and see what's causing the double-callback.

Thanks for reporting :)

**Comment by AlexandreRoba** [comment]
Thanks YOU for building all this :)

**Comment by brianegan** [comment]
Hey there -- do you happen to have a code sample that exhibits this behavior? I've written some tests and tried a few ways myself, but the `onInitialBuild` callback is only called once.

Are you perhaps creating a new StoreBuilder / StoreConnector with a Unique key on each build?

**Comment by brianegan** [comment]
Hrm, this is interesting -- since the `StoreConnector` in `MainShell` does not wrap `this.page`, when the ViewModel changes it should not cause the `Stack` with `this.page` to be rebuilt, only the code inside the `builder` function.

Could you check if `onInit` and `onDispose` on `HomeTabSearch` are also called multiple times? If so, this indicates that the `this.page` Widget's corresponding `State` class is somehow being initialized then disposed over and over. Generally, that will only happen when the `StatefulWidget` it's associated with is removed from the tree and added again, or if the `key` associated with `this.page` changes on rebuild. Do you know if either of these are a possibility?

**Comment by AlexandreRoba** [comment]
Hi Brian, I’m AFK for the next 5h. I’ll check ASAP when driving back.

**Comment by brianegan** [comment]
No worries! Whenver ya get a chance :)

**Comment by brianegan** [comment]
Hey hey :) Any update on this one @AlexandreRoba?

**Comment by AlexandreRoba** [comment]
Hi, sorry I’m on vacation will be back next week. I’ll get back to you ASAP.

**Comment by brianegan** [comment]
Oh dang, sorry to interrupt! No problem at all, please take your time :)

**Comment by AlexandreRoba** [comment]
Hi Brian, I've refactored significantly the app since and can seems to reproduce this. :(
I guess it must be something I've done wrong somewhere... Sorry for this. I suggest to cloase this one and If I face this again I will reopen it with a working exemple. Thanks for your help. cheers.

**Comment by brianegan** [comment]
Sounds good, will do! Definitely let me know if ya need more help :)
