### ISSUE TITLE
StoreConnector and rebuild of widgets. 

### ISSUE THREAD

**Issue by Nersbe** [brianegan/flutter_redux#71]
Hi,
First I apologize in advance if this should have been posted on Stackoverflow instead, feel free to close if that is the case. 
So I am trying to wrap my head around if I am handling state changes the correct way. 

So in my AppState I have a state for each of my screens. So for example I have a HomeState, that handles all the state mangement for my Home Screen.  For example HomeState consists of an active tabbar index for a tabbar and a array of data to a listview. 

The userinterface of my Home Screen has been divided into sub widgets.  A widget class with a tabbar and a widget class for a listview. These two classes furthermore consists of seperate view models, which the tabbar and listview consumes via a StoreConnector. 

My concern is that I experience that all my sub widgets on a screen is rebuild upon a single unrelated state change. For example on my HomeScreen when I click on my tabbar I update the active tabbar index in my HomeState, though this also calls a rebuild on my list.
Something I would assume should be distinct as the listview and the tabbar is driven by two different viewmodels of the HomeState. Is this intended behaviour? That the StoreConnector emits a rebuild for all widgets every time any changes happen to the store, even though this is unrelated to some widgets? If yes would this be a performance concern? 

Nevertheless, thank you for a great library.

**Comment by brianegan** [comment]
Hey there -- thanks for writing! Since everything funnels through a Single `Store`, any time the State changes, all Widgets listening to the Store (StoreConnectors, etc), will rebuild.

To change this, you can use the `distinct` option on the `StoreConnector`. It will listen for changes, but if the ViewModel hasn't changed, it won't trigger a rebuild.

Does that help answer your question?

**Comment by brianegan** [comment]
Hey @Nersbe -- did this help out?

**Comment by brianegan** [comment]
Hey there @ejabu -- do you have any code you can show me of the problem you're running into? It's easier to take a look that way!

**Comment by ejabu** [comment]
fortunately not long after, I managed to solve it.

It turn out running succesfully as I removed these two lines

```
final homeScreenScaffoldKey = new GlobalKey<ScaffoldState>(); ``<---- REMOVED``

return Scaffold(
          key: homeScreenScaffoldKey, ``<---- REMOVED``
          body : Stack(
                Positioned(
                    top: 20.0,
                    child: Container(
                        width: MediaQuery.of(context).size.width,
                        height: 83.0,
                        child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                        children: <Widget>[
                            TabBar(), ``<----- Widget with `store.dispatch` from some _ViewModel``
                        ],
                        ),
                    ),
                ),
                Positioned(
                    top: 100.0,
                    child: Container(
                        width: MediaQuery.of(context).size.width,
                        height: 83.0,
                        child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                        children: <Widget>[
                            ToDoList(), ``<----- Widget with StoreSelector from some _ViewModel``
                        ],
                        ),
                    ),
                ),

          )
       


```

In my case, TabBar will dispatch CategoryFilter. It may looks similiar to your ActiveFilter in Todo.

And then, on TodoList widget, as those ListItem get their value from TodoSelector, it will automatically filtered according to selected CategoryFilter.

The problem was, whenever I click the TabBar options, somehow the ToDoList rebuild and lost its scroll position.

Afterall, after I removed Scaffold key, it runs well.


I wonder, what is the use of Key actually in Flutter ? Got any reference of it ?
