### ISSUE TITLE
converter is not called after parent changes

### ISSUE THREAD

**Issue by jeonghoonkim** [brianegan/flutter_redux#78]
Hello 

I'm not sure this is intended... can you take a look at it?

mm... Here is sample child widget.

```
class ChildViewModel {
  ChildViewModel({this.data1, this.data2});

  final String data1;
  final String data2;
}

class ChildView extends StatefulWidget {
  final String someId;

  ChildView({
    this.someId
  });

  @override
  State<StatefulWidget> createState() => new ChildViewState();
}

class ChildViewState extends State<ChildView> {
  @override
  Widget build(BuildContext context) {
    print(widget.someId); // #1
    return new StoreConnector<ReduxState, ChildViewModel>(
      converter: (store) {
          print(widget.someId); // #2
          return ChildViewModel(data1: ..., data2: ...);
      },
      builder: (context, viewModel) {
          print(widget.someId); // #3
      }
    );
  }
}

```
If i change 'someId' value of ChildView from 'aaaa' to 'bbbb', converter is not called.
`ChildView(someId: 'aaaa') -> ChildView(someId: 'bbbb')`
then above code print like this.
```
aaaa -> #2 
bbbb -> #1
bbbb -> #3
```

**Comment by arthurgustin** [comment]
@jeonghoonkim Hi, if you test on your phone, you may have the same issue than me, sometimes the app is not built completely and I noticed I had to uninstall the app, delete the build folder from the project and rebuild, and it works

**Comment by brianegan** [comment]
Hey hey :) Hrm, that's an interesting one... The `converter` function is only called when Stream emits a change, but perhaps I should change that up. Thanks for the report!

**Comment by xqwzts** [comment]
@brianegan I ran into a use case where this would be handy, so put together a quick solution to trigger the stream on each `didUpdateWidget` call [quick implementation diff here: https://github.com/brianegan/flutter_redux/compare/master...xqwzts:rebuild_on_update].

Haven't PR'ed as I'm not sure it's the nicest way to do this, setting that `rebuildOnUpdate` flag will be pretty inefficient [especially if not used in combination with `distinct`].

**Comment by justinsilvestre** [comment]
One workaround to force an update is to give your widget a `Key` derived from the values that should trigger the update.

**Before**
```dart
ChildView(someId: 'aaaa');
```

***After***
```dart
final someId = 'aaaa';
ChildView(someId: someId, key: Key(someId));
```

**Comment by jeonghoonkim** [comment]
@justinsilvestre oh my god... that's right. Why did I not think of that before?.... Thanks!

**Comment by khainke** [comment]
Manual key management should not be the solution here, i prepared an example to highlight the problem: https://github.com/khainke/flutter_redux_multiple_counter.git (when switching the counter, the index text gets updated immediately but the displayed value will still display the old selected counter, until the next other action / add, then the converter function will get evaluated). 

This behaviour looks a bit odd to me, and was pretty unexpected to be honest. Right now im faced with some bugs because i was using the converter argument to select individual parts of lists and maps from the store, in an effort to keep the selection maximally local and small. But i probably have to select the lists and maps as a whole in the converter and actually convert them in the build method. Again, it looks odd to me. 

It should be documented, that the converter function is supposed to be immutable.
